[package]
name = "bcachectl"
version = "0.6.0"
authors = ["Jacob Riddle <useafterfree.consulting@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
failure = ">=0.1.5"
exitfailure = ">=0.5.1"
toml = ">=0.4"
serde_derive = ">=1.0"
serde = ">=1.0"